### ISSUE TITLE
Error Handling Request

### ISSUE THREAD

**Issue by umesh-timalsina** [ChimeraPy/Orchestrator#161]
The WebSocket connection from manager to worker is causing issues:

```py
Error handling request
Traceback (most recent call last):
  File "/home/umesh/mambaforge/envs/chimerapy-dev/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Bad status line "Invalid method encountered:\n\n  b'\\xff'\n    ^"
Error handling request
Traceback (most recent call last):
  File "/home/umesh/mambaforge/envs/chimerapy-dev/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Bad status line "Invalid method encountered:\n\n  b'\\xff'\n    ^"
Error handling request
Traceback (most recent call last):
  File "/home/umesh/mambaforge/envs/chimerapy-dev/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Bad status line "Invalid method encountered:\n\n  b'\\xff'\n    ^"
Error handling request
Traceback (most recent call last):
  File "/home/umesh/mambaforge/envs/chimerapy-dev/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Bad status line "Invalid method encountered:\n\n  b'\\xff'\n    ^"

```

**Comment by umesh-timalsina** [comment]
According to aiohttp devs:

- Feel free to send a PR with a reproducer, I suppose.. From the description, it seems like the tracebacks are annoying in the log, but that shouldn't affect the app operation, short of that annoyance...

We should continue to develop new features and find this bug track. Its kind of hard to reproduce this bug because of the unknown source.
